language: objective-c
before_install:
    - brew uninstall xctool
    - brew update
    - brew install xctool
script: xctool -workspace Selene.xcworkspace -scheme Selene -sdk iphonesimulator build test
